"""drop fk from checklist_items user_id

Revision ID: 02d310f5ed64
Revises: e22379f325f5
Create Date: 2026-06-26 15:54:48.869474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d310f5ed64'
down_revision: Union[str, None] = 'e22379f325f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checklist_items_user_id_fkey', 'checklist_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('checklist_items_user_id_fkey', 'checklist_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
