"""add_saved_properties

Revision ID: 14e5a192f901
Revises: 345274eb701b
Create Date: 2026-06-28 22:30:45.485146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e5a192f901'
down_revision: Union[str, None] = '345274eb701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rightmove_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=64), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('red_flag_count', sa.Integer(), nullable=False),
    sa.Column('green_flag_count', sa.Integer(), nullable=False),
    sa.Column('decoded_result', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_properties')
    # ### end Alembic commands ###
