"""Add personas, schools reference data, signal cache, property enrichment

Revision ID: 32c757f543d7
Revises: 14e5a192f901
Create Date: 2026-08-19 10:10:43.513470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c757f543d7'
down_revision: Union[str, None] = '14e5a192f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('preset_key', sa.String(length=64), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('min_bedrooms', sa.Integer(), nullable=False),
    sa.Column('needs_outdoor_space', sa.Boolean(), nullable=False),
    sa.Column('needs_parking', sa.Boolean(), nullable=False),
    sa.Column('property_types', sa.JSON(), nullable=False),
    sa.Column('min_lease_years', sa.Integer(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('workplaces', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('schools',
    sa.Column('urn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('establishment_type', sa.String(length=128), nullable=True),
    sa.Column('easting', sa.Integer(), nullable=False),
    sa.Column('northing', sa.Integer(), nullable=False),
    sa.Column('local_authority', sa.String(length=128), nullable=True),
    sa.Column('ofsted_rating', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('urn')
    )
    op.create_index(op.f('ix_schools_easting'), 'schools', ['easting'], unique=False)
    op.create_index(op.f('ix_schools_northing'), 'schools', ['northing'], unique=False)
    op.create_table('signal_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_cache_cache_key'), 'signal_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_signal_cache_expires_at'), 'signal_cache', ['expires_at'], unique=False)
    # Autogenerate also proposed dropping the legacy 'users' and 'analyses'
    # tables, whose models were removed in an earlier commit. Left in place
    # deliberately — this migration is additive, and retiring those tables
    # should be its own reviewed change rather than a side effect of this one.
    op.add_column('saved_properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('saved_properties', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('saved_properties', sa.Column('enrichment', sa.JSON(), nullable=True))
    op.add_column('saved_properties', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.add_column('saved_properties', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('saved_properties', sa.Column('fit_coverage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_properties', 'fit_coverage')
    op.drop_column('saved_properties', 'fit_score')
    op.drop_column('saved_properties', 'persona_id')
    op.drop_column('saved_properties', 'enrichment')
    op.drop_column('saved_properties', 'longitude')
    op.drop_column('saved_properties', 'latitude')
    op.drop_index(op.f('ix_signal_cache_expires_at'), table_name='signal_cache')
    op.drop_index(op.f('ix_signal_cache_cache_key'), table_name='signal_cache')
    op.drop_table('signal_cache')
    op.drop_index(op.f('ix_schools_northing'), table_name='schools')
    op.drop_index(op.f('ix_schools_easting'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
