"""drop fk from journeys user_id

Revision ID: 345274eb701b
Revises: 02d310f5ed64
Create Date: 2026-06-28 21:35:45.545478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345274eb701b'
down_revision: Union[str, None] = '02d310f5ed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journeys_user_id_fkey', 'journeys', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('journeys_user_id_fkey', 'journeys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
