"""add category to checklist_items

Revision ID: e22379f325f5
Revises: 51d8951d5376
Create Date: 2026-06-26 15:48:22.404385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22379f325f5'
down_revision: Union[str, None] = '51d8951d5376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('category', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_items', 'category')
    # ### end Alembic commands ###
