"""Track whether a listing is still active

Revision ID: edac2b405a87
Revises: 32c757f543d7
Create Date: 2026-08-19 10:58:16.723653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edac2b405a87'
down_revision: Union[str, None] = '32c757f543d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: existing rows have no value, and
    # a bare NOT NULL add fails on any table that already holds data. Properties
    # saved before this column existed were all still listed at the time.
    op.add_column(
        'saved_properties',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_properties', 'is_active')
    # ### end Alembic commands ###
